#ifndef POLAROIDMAKER_GLOBAL_H
#define POLAROIDMAKER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(POLAROIDMAKER_LIBRARY)
#define POLAROIDMAKER_EXPORT Q_DECL_EXPORT
#else
#define POLAROIDMAKER_EXPORT Q_DECL_IMPORT
#endif

#endif  // POLAROIDMAKER_GLOBAL_H
